stages:
  - lint
  - build
  - test

default:
  image: ubuntu:20.04
  before_script:
    - apt-get update --yes

lint:
  stage: lint
  script:
    - apt-get install --yes clang-format cppcheck
    - ./scripts/dev-lint.sh
  timeout: 3 minutes

build:
  stage: build
  script:
    - DEBIAN_FRONTEND=noninteractive apt-get install --yes python3-pip cmake git make
    - pip3 install conan==1.60.2
    - conan profile new default --detect
    - conan profile update settings.compiler.libcxx=libstdc++11 default
    - ./scripts/build-dlx.sh
    - ./scripts/build-cadical.sh
    - ./scripts/build-cryptominisat.sh
    - ./scripts/build-kissat.sh
    - ./scripts/build-breakid.sh
    - ./scripts/build-sbva.sh
    - ./scripts/build-pblib.sh
    - ./scripts/dev-setup.sh -DGUROBI=OFF -DMINIZINC=OFF
    - ./scripts/dev-build.sh
  artifacts:
    paths:
      - build
  timeout: 10 minutes

test:
  stage: test
  script:
    - ./scripts/dev-test.sh
  timeout: 3 minutes

release:
  when: manual
  stage: lint
  script:
    - DEBIAN_FRONTEND=noninteractive apt-get install --yes python3-pip cmake git make
    - pip3 install conan==1.60.2
    - conan profile new default --detect
    - conan profile update settings.compiler.libcxx=libstdc++11 default
    - ./scripts/build-dlx.sh
    - ./scripts/build-cadical.sh
    - ./scripts/build-cryptominisat.sh
    - ./scripts/build-kissat.sh
    - ./scripts/build-breakid.sh
    - ./scripts/build-sbva.sh
    - ./scripts/build-pblib.sh
    - ./scripts/release-setup.sh -DGUROBI=OFF -DMINIZINC=OFF
    - ./scripts/release-build.sh
  artifacts:
    paths:
      - release
  timeout: 10 minutes
