#include "help_strings.hpp"

#include <string>

const std::string help_strings::kNamedTilesList =
        "Monomino, Domino, Trominoes                                      \n"
        "                                                                 \n"
        " 1: x    2: x    3I: x    3L: x                                  \n"
        "            x        x        xx                                 \n"
        "                     x                                           \n"
        "                                                                 \n"
        "Tetrominoes                                                      \n"
        "                                                                 \n"
        " 4I: x   4J:  x   4L: x    4O:  xx   4S:  xx   4T: xxx   4Z: xx  \n"
        "     x        x       x         xx       xx         x         xx \n"
        "     x       xx       xx                                         \n"
        "     x                                                           \n"
        "                                                                 \n"
        "Pentominoes                                                      \n"
        "                                                                 \n"
        " 5A:  x     5F:  xx    5G: x      5J:  x     5P: xx     5S:  xx  \n"
        "      x         xx         xx          x         xx          x   \n"
        "     xx          x          x          x         x          xx   \n"
        "      x                     x         xx                         \n"
        "                                                                 \n"
        " 5Y:  x     5R: xx     5N:  x     5L: x      5Q: xx     5Z: xx   \n"
        "     xx          xx        xx         x          xx          x   \n"
        "      x          x         x          x           x          xx  \n"
        "      x                    x          xx                         \n"
        "                                                                 \n"
        " 5I: x      5T: xxx    5U: x x    5V: x      5W: x      5X:  x   \n"
        "     x           x         xxx        x          xx         xxx  \n"
        "     x           x                    xxx         xx         x   \n"
        "     x                                                           \n"
        "     x                                                           \n";
